### ISSUE TITLE
No logs, no requests made to S3, no exceptions thrown

### ISSUE THREAD

**Issue by MarneeDear** [serilog-contrib/Serilog.Sinks.AmazonS3#4] opened 2019-10-05 21:03 UTC
I have setup a simple console app on .NET Core to test using this library with Serilog. I have added all of the relevant references and the code. When I do anything like `Log.Error("ERROR")`, I do not get any logs in S3 and no exceptions seem to be thrown.

I also started Fiddler to see what kinds of requests are made while the program is running, but none are made.

You can see my sample project here
https://github.com/MarneeDear/s3-serilog-example

The code is here
https://github.com/MarneeDear/s3-serilog-example/blob/master/src/console/Program.fs

You can probably run it by cloning the repo and doing

```
dotnet restore
dotnet run
```

Am I doing something wrong?

Thank you.

**Comment by MarneeDear** [comment] 2019-10-05 21:08
Please also note that the other sinks I am using are working. I am using Console and File.

**Comment by SeppPenner** [comment] 2019-10-07 07:23
Mhm, from the first view, it looks alright. Did you set the bucket permissions correctly (e.g. let the sink write to the bucket)?

I already saw this issue once with my own test project but wasn't able to reproduce it...

**Comment by codingbadger** [comment] 2019-11-11 19:09
I get the same behaviour using .NET Core 2.2 in console app. I am using AWS creds that have admin access

No errors, nothing on S3 but a local file is created and updated.

```           
logger = new LoggerConfiguration()
                        .WriteTo.AmazonS3(
                            "log.txt",
                            "some-bucket-name",
                            Amazon.RegionEndpoint.EUWest1,
                            rollingInterval: RollingInterval.Day,
                            failureCallback:  e => Console.WriteLine($"Sink error: {e.Message}")
                        )
                        .CreateLogger();

                        logger.Error("Foo");
```

**Comment by SeppPenner** [comment] 2019-11-11 19:14
I still don't know where this comes from. I will check it again, but can't promise anything here...

**Comment by codingbadger** [comment] 2019-11-11 20:25
Hi @SeppPenner  

I think there might be a misunderstanding of how this works. I expected any log file change to be uploaded to S3 but that doesn't appear to be the case. It looks like the upload is done whenever there is a new checkpoint in the `RollingSinkFile.PathRoller`?

So if I set the interval to `RollingInterval.Minute` then the file is uploaded to S3 every minute. If I set it to `RollingInterval.Day` I presume the file is uploaded once a day?

**Comment by SeppPenner** [comment] 2019-11-12 08:14
> So if I set the interval to RollingInterval.Minute then the file is uploaded to S3 every minute. If I set it to RollingInterval.Day I presume the file is uploaded once a day?

@codingbadger That's how it should work. I have used the [Serilog.Sinks.PeriodicBatching](https://github.com/serilog/serilog-sinks-file) for that.

I decided to use this mechanism because uploading every single log event would mean to create one file per event (Which I assumed was a bit too much).

However, I'm not sure yet if there is an error in my mechanism because I once experienced the behaviour that no files were uploaded despite the files were created locally and should have been transferred (No errors or exceptions) but the S3 bucket was empty... That might be the case in @MarneeDear's situation as well. I wasn't yet able to reproduce this behaviour though.

I have this issue on my list and will check it again hopefully soon.

**Comment by codingbadger** [comment] 2019-11-12 08:32
Maybe adding an option to enable all events to be pushed up to S3 immediately?

For my situation, I only want one file per day created but I want it to replicated on S3 immediately so I don't lose any events and I can view them straight away on S3.

If you amend your test to `RollingInterval.Day` you will see the behaviour of the file not being uploaded to S3. This is because the `currentCheckpoint` is 12th Nov 2019 and the `nextCheckpoint` is 13th Nov 2019 so the file is opened but not sent to S3.

**Comment by SeppPenner** [comment] 2019-11-12 08:43
@codingbadger Ok, I understand the problem now. I will try to provide a solution soon. I hope I can do it today already.

**Comment by codingbadger** [comment] 2019-11-12 08:45
I have got an example of pushing up every change if you want me to submit a PR?

**Comment by SeppPenner** [comment] 2019-11-12 08:46
> I have got an example of pushing up every change if you want me to submit a PR?

Yeah sure :)

**Comment by SeppPenner** [comment] 2019-11-12 18:23
@codingbadger I have updated the package. It should be available soon.

@MarneeDear Could you please check if your issue is related? If not, please contact me again. I will close this issue for now.

**Comment by rameshdabhi** [comment] 2020-08-18 10:21
@SeppPenner I am facing the same issue. I am using a C# webforms application. I created a small test application and tried to log on the click of a button.
I can see the files created locally in the `C:\Program Files (x86)\IIS Express\` folder, however the same are not being sent to the S3 bucket. I have kept the RollingInterval to a minute's time.

Below is the code I am using for test purpose.

```
        protected void btnLog_Click(object sender, EventArgs e)
        {
            using (var logger = new Serilog.LoggerConfiguration()
                .MinimumLevel.Verbose()
                .WriteTo.AmazonS3(formatter: new CompactJsonFormatter(),
                path: "testlog.json",
                bucketName: "<bucket-name>",
                endpoint: RegionEndpoint.USEast1,
                awsAccessKeyId: "<myawsAccessKeyId>",
                awsSecretAccessKey: "<myawsSecretAccessKey>",
                bucketPath: "<my-sub-folder-name>",
                failureCallback: new Action<Exception>(ex => { System.IO.File.AppendAllText(Server.MapPath("~/failureCallback.txt"), $"{Environment.NewLine}{DateTime.Now:ddMMyyyy HH:mm:ss.fff} - {ex}"); }),
                rollingInterval: Serilog.Sinks.AmazonS3.RollingInterval.Minute
                )
                .CreateLogger()
                )
            {
                logger.Information(txtLog.Text);
            }
        }
```

If more then one event is logged within a minute, then the below exception is received in the SelfLog.
`2020-08-18T10:02:41.8298855Z File target C:\Program Files (x86)\IIS Express\testlog202008181532.json was locked, attempting to open next in sequence (attempt 1).`

If I use the `autoUploadEvents:true` option, then the file is uploaded on the S3 bucket immediately. However, the code blocks at the `logger.Information(txtLog.Text);` statement and doesn't execute further,

Please let me know if I am missing something.
Thanks.

**Comment by SeppPenner** [comment] 2020-08-19 18:25
Hi @rameshdabhi. I will have a look at this but not within the next week (I'm too busy at the moment). I will see what I can do then.

**Comment by SeppPenner** [comment] 2020-09-27 17:06
@rameshdabhi I guess I found where the issue comes from, but I'm not sure yet how to handle it. The issue seems to be that I use this line of code https://github.com/SeppPenner/Serilog.Sinks.AmazonS3/blob/681ce1438e0fd8cef46952af23fa486c89d19076/src/Serilog.Sinks.AmazonS3/Sinks/AmazonS3/RollingFileSink.cs#L427 as `this.UploadFileToS3().Wait();` in a void method as I somehow need to wait for that task. The problem is, I can't make `void Emit` async as a `lock` statement is used and I it's not poossible to await a task inside a lock. I will search for a solution now...

**Comment by SeppPenner** [comment] 2020-09-27 20:35
The problem is something different. Sometimes, not all files are uploaded. I didn't find the issue yet.

**Comment by rameshdabhi** [comment] 2020-09-28 06:05
@SeppPenner I'm very hopeful that you'll find that. :)

**Comment by SeppPenner** [comment] 2020-09-29 06:58
I guess, it's some kind of threading / timing issue mainly caused by the fact that the `Emit()` method is not async. If I add a larger number of files to be kept (e.g. `retainedFileCountLimit = 200`), this does seem to work properly... This definitely needs more investigation, maybe I also have to change things in the rolling file sink a bit.

**Comment by SeppPenner** [comment] 2020-11-09 09:36
I'm currently reworking this sink and let's see if the issue is fixed afterwards.

**Comment by SeppPenner** [comment] 2020-11-09 19:18
After my changes, I can't even upload anymore... I will check again tomorrow.

**Comment by SeppPenner** [comment] 2021-02-03 21:21
There is a new version out soon. I hope that this will fix the issues. If not, I will try to reproduce the issue again and talk to the main developer(s) of Serilog if they find  some issue(s).

**Comment by rameshdabhi** [comment] 2021-02-04 11:03
Yep, hope for the best!! \m/

**Comment by SeppPenner** [comment] 2021-02-21 15:11
I will close this now, if there are still issues, just open a new issue or tell me to re-open this one and I will have a look.

**Closed as completed by SeppPenner** 2021-02-21 15:11 UTC
Labels: bug
