### ISSUE TITLE
Getting an error Input string was not in a correct format on every logging statement

### ISSUE THREAD

**Issue by alexgurman** [serilog-contrib/Serilog.Sinks.AmazonS3#22] opened 2021-07-21 20:55 UTC
Full error:

Input string was not in a correct format.    at System.Text.StringBuilder.FormatError()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object arg0, Object arg1, Object arg2)
   at Serilog.Debugging.SelfLog.WriteLine(String format, Object arg0, Object arg1, Object arg2)
   at Serilog.Sinks.AmazonS3.AmazonS3Sink.EmitBatchAsync(IEnumerable`1 batch)

Reproduceable in any configuration - see example below, any logging statement. Everything gets written correctly, regardless.

loggerConfiguration.WriteTo.AmazonS3(
                bucketFile,
                cfg.BucketName,
                Region,
                awsCreds.AccessKey,
                awsCreds.SecretKey,
                LogEventLevel.Debug,
                "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u3}] {Message:lj}{NewLine}{Exception}");

Logger?.Information("deleting all files from bucket");

**Comment by SeppPenner** [comment] 2021-07-25 19:51
I'm not yet sure where this comes from (And I have added a test and cannot reproduce the scenario yet). My assumption is that either `SelfLog.WriteLine($"Uploaded data to Amazon S3 with result: {JsonConvert.SerializeObject(result)}.");` or `SelfLog.WriteLine($"{ex.Message} {ex.StackTrace}");` in `AmazonS3Sink.cs` fails.

**Comment by alexgurman** [comment] 2021-07-25 21:00
I can see results of logging statement in S3 bucket, so confused.

**Comment by SeppPenner** [comment] 2021-08-01 19:14
> I can see results of logging statement in S3 bucket, so confused.

Haha okay... I have no idea :D If you manage to get a minimum working example, this would be really great since I wasn't able to reproduce this yet.

**Comment by KindOfANiceGuy** [comment] 2021-08-26 22:49
I was also encountering this error so I built and ran the assembly from source. In `AmazonS3Sink.cs`, line 90, the code is serializing the S3 response as a Json string and attempting to pass it into `SelfLog.WriteLine()` which uses `string.Format()` under the hood. The exception is caused by un-escaped curly braces in the Json string. If you disable SelfLog in your Serilog configuration, you won't experience the issue.

Personally, I don't see how logging the entire S3 response is useful - seems like a generic success message could be logged instead but even that I wouldn't deem necessary. I'll leave that call up to the maintainer. The other option is to properly escape the curly braces.

**Comment by alexgurman** [comment] 2021-08-26 23:35
thank you

**Comment by SeppPenner** [comment] 2021-08-29 08:01
> 
> 
> I was also encountering this error so I built and ran the assembly from source. In `AmazonS3Sink.cs`, line 90, the code is serializing the S3 response as a Json string and attempting to pass it into `SelfLog.WriteLine()` which uses `string.Format()` under the hood. The exception is caused by un-escaped curly braces in the Json string. If you disable SelfLog in your Serilog configuration, you won't experience the issue.
> 
> Personally, I don't see how logging the entire S3 response is useful - seems like a generic success message could be logged instead but even that I wouldn't deem necessary. I'll leave that call up to the maintainer. The other option is to properly escape the curly braces.

If you ask me personally, I haven't used SelfLog at all until now :D I remember that someone wanted to have this as logging output, but I agree to remove the call now as it doesn't make sense. Escaping the curly braces is a workaround, but unnecessary if you ask me. Let's just remove the logging and see if someone complains 😅

**Comment by SeppPenner** [comment] 2021-08-29 08:23
This is changed / fixed in version 1.1.10. I try to fix the other issue with the file sizes now.

**Closed as completed by SeppPenner** 2021-08-29 08:23 UTC
Labels: bug
